language: node_js
node_js:
  - "6"
  - "8"
install:
  - npm install
  - cd docs; npm install; cd ..
script:
  - npm test
  - npm run benchmark -- -g dont-actually-run-benchmarks
  - cd docs; npm run make; cd ..
  - git status
  - git diff
  - git diff-index --quiet HEAD -- . || (echo "$(tput bold)$(tput setaf 4)Did you forget to rebuild the docs?   $ cd docs; npm run make$(tput sgr0)"; exit 1)
cache:
  directories:
    - "node_modules"
